preset: psr2

enabled:
    - align_phpdoc
    - binary_operator_spaces
    - blank_line_after_opening_tag
    - blank_line_before_return
    - cast_spaces
    - concat_without_spaces
    - declare_equal_normalize
    - declare_strict_types
    - function_typehint_space
    - hash_to_slash_comment
    - heredoc_to_nowdoc
    - include
    - length_ordered_imports
    - lowercase_cast
    - lowercase_static_reference
    - magic_constant_casing
    - magic_method_casing
    - method_separation
    - native_function_casing
    - native_function_type_declaration_casing
    - no_alias_functions
    - no_blank_lines_after_class_opening
    - no_blank_lines_after_phpdoc
    - no_blank_lines_after_throw
    - no_blank_lines_between_imports
    - no_blank_lines_between_traits
    - no_empty_phpdoc
    - no_empty_statement
    - no_extra_consecutive_blank_lines
    - no_leading_import_slash
    - no_leading_namespace_whitespace
    - no_multiline_whitespace_around_double_arrow
    - no_multiline_whitespace_before_semicolons
    - no_short_bool_cast
    - no_singleline_whitespace_before_semicolons
    - no_spaces_inside_offset
    - no_trailing_comma_in_list_call
    - no_trailing_comma_in_singleline_array
    - no_unneeded_control_parentheses
    - no_unreachable_default_argument_value
    - no_unused_imports
    - no_useless_return
    - no_whitespace_before_comma_in_array
    - no_whitespace_in_blank_line
    - normalize_index_brace
    - not_operator_with_successor_space
    - object_operator_without_whitespace
    - phpdoc_indent
    - phpdoc_no_access
    - phpdoc_no_package
    - phpdoc_no_useless_inheritdoc
    - phpdoc_scalar
    - phpdoc_summary
    - phpdoc_to_comment
    - phpdoc_trim
    - phpdoc_type_to_var
    - phpdoc_types
    - phpdoc_var_without_name
    - post_increment
    - print_to_echo
    - self_accessor
    - short_array_syntax
    - short_list_syntax
    - short_scalar_cast
    - single_blank_line_before_namespace
    - single_quote
    - space_after_semicolon
    - standardize_not_equals
    - ternary_operator_spaces
    - trailing_comma_in_multiline_array
    - trim_array_spaces
    - unary_operator_spaces
    - whitespace_after_comma_in_array

disabled:
    - alpha_ordered_imports
    - simplified_null_return
    - phpdoc_inline_tag
    - phpdoc_single_line_var_spacing
