preset: laravel

enabled:
    - declare_strict_types

disabled:
    - unalign_equals
    - alpha_ordered_imports
    - simplified_null_return
    - phpdoc_inline_tag
    - phpdoc_single_line_var_spacing
